spring:
  application:
    name: dubbo-provider
  main:
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: com.lzj.spring.cloud.alibaba.dubbo.provider.service
  protocol:
    name: dubbo
    port: 20881
    serialization: kryo
  provider:
    loadbalance: roundrobin
  registry:
    address: nacos://127.0.0.1:8848